name: example

on: [push]

jobs:

  hello_world_job:
    runs-on: ubuntu-latest
    name: 挨拶するジョブ
    steps:
    - name: Hello world action step
      id: hoge
      uses: Kurom96/action-hello@test
      with:
        your-name: '太郎'
    - name: Get the output time
      run: |
        echo "挨拶した時間： ${{ steps.hoge.outputs.time }}"
